version: '3'

env:
  GIN_MODE: release

tasks:
  start:
    cmds:
      - go run main.go
    silent: true
  test:
    cmds:
      - go test -v ./...
    silent: true
  dbuild:
    cmds:
      - docker build -t authpulse:local .
    silent: true
  dstart:
    cmds:
      - docker run -p 8080:8080 -e GIN_MODE -e DATABASE_HOST=host.docker.internal authpulse:local
