version: '3'

dotenv: ['.env']

tasks:
  start:
    cmds:
      - go run main.go
    silent: true
  test:
    cmds:
      - go clean -testcache
      - go test -v ./...
    silent: true
  dbuild:
    cmds:
      - docker build -t authpulse:local .
    silent: true
  dstart:
    cmds:
      - docker run -p 8080:8080 --env-file .env -e DATABASE_HOST=host.docker.internal authpulse:local
