name: AuthPulse CI

on:
  push:
    branches:
      - master
  pull_request:
    branches:

env:
  GOLANG_VERSION: 1.19

jobs:
  linter:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/setup-go@v3
      with:
        go-version: "${{ env.GOLANG_VERSION }}"
    - uses: actions/checkout@v3
    - name: golangci-lint
      uses: golangci/golangci-lint-action@v3
  tests:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-go@v3
      with:
        go-version: "${{ env.GOLANG_VERSION }}"
    - name: Run tests
      run: go test -v ./...
